upstream client {
    server node-client:8000;
}
upstream api {
    server node-server:9000;
}
 
server {
    listen 80;
    location / {
        proxy_pass http://client;
    }
    location /api/ {
        proxy_pass http://api;
    }
}
