name: Ajax-Trains
services:
  client:
    image: nginx
    volumes:
      - ./client:/usr/share/nginx/html.ro
    ports:
      - "80:80"
  server:
    image: node:22.9.0
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "82:9000"
    command: sh -c "
      chmod +x run.sh &&
      ./run.sh"