name: Ajax-Trains
services:
  node-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    ports:
      - "81:8100"
    command: sh -c "
      chmod +x run.sh &&
      ./run.sh"

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "82:9000"
    command: sh -c "
      chmod +x run.sh &&
      ./run.sh"
  
  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - node-client
      - node-server